'''
Created on Oct 29, 2015

@author: yangke
'''
from model.TaintVar import TaintVar
from TraceTrackTest import TraceTrackTest
class Test_swfdump_t__data_258:
    
    '''
    This is a test for the trace generated by exploit_258_0 of swfdump which is caused by null pointer t->data.
    Note that the root cause is the negative value initiated in 'for' statement of function swf_GetBits.
    -----------------------------------------------------------------
    U32 swf_GetBits(TAG * t,int nbits):lib/rfxswf.c:202
    
    211      int i,m=t->len>10?10:t->len;
    212      for(i=-1;i<m;i++) {
                    ^ 
    213        fprintf(stderr, "(%d)%02x ", i, t->data[i]);
                                                    ^
    ------------------------------------------------------------------
    Stack Trace:
    #0  0x08064e35 in swf_GetBits (t=0x80fe008, nbits=5) at rfxswf.c:214
    #1  0x080660b9 in swf_GetRect (t=0x80fe008, r=0xbfffda38) at rfxswf.c:693
    #2  0x0805a6a4 in swf_FontExtract_DefineTextCallback (id=0, f=0x80fe0a0, 
        t=0x80fe008, jobs=2, callback=0x0, self=0x0) at modules/swftext.c:454
    #3  0x0805aa55 in swf_FontExtract_DefineText (id=0, f=0x80fe0a0, t=0x80fe008, 
        jobs=2) at modules/swftext.c:532
    #4  0x0805ae27 in swf_FontExtract (swf=0x80f9ce0 <swf>, id=0, font=0x80fe090)
        at modules/swftext.c:617
    #5  0x0804cc73 in fontcallback2 (self=0x0, id=0, name=0xbfffe32b "")
        at swfdump.c:926
    #6  0x0805972d in swf_FontEnumerate (swf=0x80f9ce0 <swf>, 
        FontCallback=0x804cc2f <fontcallback2>, self=0x0) at modules/swftext.c:133
    #7  0x0804dfd2 in main (argc=3, argv=0xbfffe804) at swfdump.c:1281
    '''
    
    def test(self):
        passed_message="SWFTOOLS-0.9.2 't->data' in 't->data[i]' TEST PASSED!"
        not_pass_message="ERRORS FOUND DURING SWFTOOLS-0.9.2 't->data' in 't->data[i]' TEST!"
        answer_path='answers/swftools-0.9.2/swfdump/'
        name='swftools-0.9.2_swfdump_t-data_258'
        logfile_path="gdb_logs/swftools-0.9.2/swfdump/gdb-swfdump_t-data_i_258.txt"
        c_proj_path='gdb_logs/swftools-0.9.2/swftools-0.9.2'
        taintVars=[TaintVar("t->data",["*"])]
        test=TraceTrackTest(answer_path,name,logfile_path,taintVars,passed_message,not_pass_message)
        test.set_c_proj_path(c_proj_path)
        passed=test.test()
        return passed
if __name__ == '__main__':
    test=Test_swfdump_t__data_258()
    test.test()