'''
Created on Oct 29, 2015

@author: yangke
'''
from model.TaintVar import TaintVar
from TraceTrackTest import TraceTrackTest
class Test_swfdump_t__data_0:
    
    '''
    This is a test for the trace generated by exploit_0_0 of swfdump which is caused by null pointer t->data.
    Note that the root cause is the negative value initiated in 'for' statement of function swf_GetBits.
    -----------------------------------------------------------------
    U32 swf_GetBits(TAG * t,int nbits):lib/rfxswf.c:202
    
    211      int i,m=t->len>10?10:t->len;
    212      for(i=-1;i<m;i++) {
                    ^ 
    213        fprintf(stderr, "(%d)%02x ", i, t->data[i]);
                                                    ^
    ------------------------------------------------------------------
    Stack Trace:
    #0  0x08064e35 in swf_GetBits (t=0x80fe008, nbits=1) at rfxswf.c:214
    #1  0x08066a2c in swf_GetMatrix (t=0x80fe008, m=0xbfffe418) at rfxswf.c:848
    #2  0x0804c637 in handlePlaceObject (tag=0x80fe008, 
        prefix=0xbfffe63c ' ' <repeats 16 times>) at swfdump.c:816
    #3  0x0804f45f in main (argc=3, argv=0xbfffe804) at swfdump.c:1589
    '''
    
    def test(self):
        passed_message="SWFTOOLS-0.9.2 't->data' in 't->data[i]' TEST PASSED!"
        not_pass_message="ERRORS FOUND DURING SWFTOOLS-0.9.2 't->data' in 't->data[i]' TEST!"
        answer_path='answers/swftools-0.9.2/swfdump/'
        name='swftools-0.9.2_swfdump_t-data_0'
        logfile_path="gdb_logs/swftools-0.9.2/swfdump/gdb-swfdump_t-data_i_0.txt"
        c_proj_path='gdb_logs/swftools-0.9.2/swftools-0.9.2'
        taintVars=[TaintVar("t->data",["*"])]
        test=TraceTrackTest(answer_path,name,logfile_path,taintVars,passed_message,not_pass_message)
        test.set_c_proj_path(c_proj_path)
        passed=test.test()
        return passed
if __name__ == '__main__':
    test=Test_swfdump_t__data_0()
    test.test()